version: '3.7'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - '3306:3306'
